---
title: "R Notebook"
output: html_notebook
---

# load the tsv data into a dataframe called mygenes.
# install the package 'plotly'
```{r}
mygenes <- read.table('gene_dist_head.tsv',header=TRUE)
install.packages('plotly')
```

# put in a summary of my genes into a data frame
```{r}
summary(mygenes)

```

# Test_graph.r script
```{r}
library(ggplot2) # We load in libraries
library(plotly)
# We define a factor set of autosomes
autosomes<-c("1","2","3","4","5","6","7","8","9","10",
 "11","12","13","14","15","16","17","18","19","20","21","22")  
# We create a new dataframe called 'genes' which only has autosomes, however we still have those additional factors
genes<- mygenes[ which(mygenes$chr %in% autosomes), ] 
# We remove the factors and then order them so they are numerical order and not alphabetical
genes$chr <- factor(genes$chr, levels = autosomes) 
 # We plot in ggplot 
ggplot(data = genes) +  geom_bar(mapping = aes(x = chr, fill = feature), width = 1)
```

# lets go to polar coordinates:
```{r}
ggplot(data = genes) +
 geom_bar(mapping = aes(x = chr, fill = feature), width = 1) +
 coord_polar()
```

# using ggplotly to create interactive grap:
```{r}
aa<-ggplot(data = genes) +  geom_bar(mapping = aes(x = chr, fill = feature), width = 1)
ggplotly(aa)
```
